
title: Mayanka Sheoran
url: 'http://Mayanka-Sheoran.github.io'
baseurl: '/Mayanka-Sheoran.github.io' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Mayanka Sheoran
tagline: Fronend Developer, Mckinsey Digital Labs
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: mayanka.sheoran@gmail.com
phone: +91 9894226919
website: mayanka.co #do not add http://
linkedin: mayanka-sheoran
github: mayanka-sheoran


# Tracker
analytics: UA-105298524-1
#Update all the sections by editing the files inside _includes folder.
